[package]
name = "wl-usi-base"
edition.workspace = true
version.workspace = true

[dependencies]
lilium-sys.workspace = true
uuid = { version = "1.13.1", features = ["v5"] }
wl-impl.workspace = true
cfg-match.workspace = true

[lib]
crate-type = ["cdylib"]
