[package]
name = "wl-usi-kmgmt"
edition.workspace = true
version.workspace = true

[dependencies]
wl-impl.workspace = true
lilium-sys.workspace = true
bytemuck.workspace = true

[lib]
crate-type = ["cdylib"]
