[build]
rustflags = [
    "-C",
    "prefer-dynamic",
    "-C",
    "relro-level=off",
    "-Ztls-model=initial-exec",
    "-C",
    "panic=abort",
]
target = ["x86_64-unknown-linux-none"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]
