[package]
name = "wl-usi-thread"
edition.workspace = true
version.workspace = true

[dependencies]
wl-impl.workspace = true
lilium-sys.workspace = true
linux-syscall.workspace = true
bytemuck.workspace = true
