[build]
rustflags = [
    "-C",
    "prefer-dynamic",
    "-C",
    "relro-level=off",
    "-Ztls-model=initial-exec",
]

[unstable]
# build-std = ["core", "alloc", "panic_abort", "std"]
# build-std-features = ["panic_immediate_abort"]
