[package]
name = "wl-usi-process"
edition.workspace = true
version.workspace = true
build = "../build-usi-lib.rs"

[dependencies]
wl-impl.workspace = true
lilium-sys.workspace = true
linux-syscall.workspace = true

[lib]
crate-type = ["cdylib"]
