#!/bin/sh

case "$0" in
    *[/\\]*)
        prg="$0"
        ;;
    *)
        prg="$(command -v "$0")"
        ;;
esac
whereami="$(dirname "$prg")"

echo "$prg"

exec "${REALGCC:-gcc}" -isystem "$whereami/../musl/include/" -isystem "$whereami/../musl/obj/include/" -isystem "$@" -specs "$whereami/../musl/lib/musl-gcc.specs"